name: Sign Artifact

on:
  workflow_call:
    secrets:
      registry-user:
            required: true
            type: string
      registry-password:
            required: true
            type: string
    inputs:
      subject-name:
            required: true
            type: string
      subject-digest:
            required: true
            type: string
      registry-url:
            required: true
            type: string

jobs:
  sign-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
    - name: Log in to registry
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ inputs.registry-user }}
        password: ${{ secrets.registry-password }}
        registry: ${{ secrets.registry-url }}

    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ inputs.subject-name }}
        subject-digest: ${{ inputs.subject-digest }}
        push-to-registry: true
